class Solution {
public:
//to remember
// trailing zeroes are generated by pairs of 2s and 5s in the factors. 
// Since there are usually more factors of 2 than 5 in the prime factorization of integers
// the number of trailing zeroes is determined by the number of factors of 5.

    int trailingZeroes(int n) {
        int count=0;
        while(n/5){
            count+=n/5;
            n/=5;
        }

        return count;
    }
};